[package]
name = "rswift-matter"
description = "Apple Matter — smart home connectivity from Rust"
version = "0.0.1"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/eugenehp/rswift"

[lib]
name = "matter"

[dependencies]
apple-sys-helpers = { workspace = true }

[lints]
workspace = true
