[package]
name = "gamesave"
description = "Apple GameSave — game save management from Rust"
version = "0.0.1"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/eugenehp/rswift"

[lib]
name = "gamesave"

[dependencies]
apple-objc-sys = { path = "../apple-objc-sys" }

[lints]
workspace = true

[build-dependencies]
swift-helper-build = { path = "../swift-helper-build" }
