[package]
name = "translation"
description = "Apple Translation — text translation from Rust"
version = "0.0.1"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/eugenehp/rswift"

[lib]
name = "translation"

[dependencies]

[build-dependencies]
swift-helper-build = { path = "../swift-helper-build" }

[lints]
workspace = true
