[package]
name = "rswift-messages"
description = "Apple Messages — iMessage app extensions from Rust"
version = "0.0.1"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/eugenehp/rswift"

[lib]
name = "messages"

[dependencies]
apple-sys-helpers = { workspace = true }

[lints]
workspace = true
