[package]
name = "rswift-metal"
description = "Apple Metal — GPU programming from Rust"
version = "0.0.1"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/eugenehp/rswift"
keywords = ["metal", "gpu", "compute", "graphics", "apple"]

[lib]
name = "metal"

[dependencies]
libc = "0.2"

[[example]]
name = "gpu_compute"
path = "examples/gpu_compute.rs"

[lints]
workspace = true

[build-dependencies]
swift-helper-build = { path = "../swift-helper-build" }
