[package]
name = "rswift-avfaudio"
description = "Alias for avfaudio — re-exports the avfaudio crate under the rswift- namespace"
version = "0.0.1"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/eugenehp/rswift"

[lib]
name = "rswift_avfaudio"

[dependencies]
avfaudio = { path = "../avfaudio" }


[[example]]
name = "check"
path = "examples/check.rs"

[lints]
workspace = true
