[package]
name = "swift-helper-build"
description = "Build-time helper: compile and link the Swift helper dylib"
version = "0.0.2"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/eugenehp/rswift"

[dependencies]
apple-platforms = { version = "0.0.4", path = "../apple-platforms" }
cc = "1"

[lints]
workspace = true
