[package]
name = "rswift-corebluetooth"
description = "Apple Core Bluetooth — BLE from Rust"
version = "0.0.1"
edition = "2021"
license = "GPL-3.0"
repository = "https://github.com/eugenehp/rswift"

[lib]
name = "corebluetooth"

[dependencies]
apple-objc-sys = { path = "../apple-objc-sys" }

[lints]
workspace = true
